package cn.zl.dao;

import cn.zl.domain.Case;
import cn.zl.domain.CaseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_case
     *
     * @mbggenerated Thu Mar 22 17:08:44 CST 2018
     */
    int countByExample(CaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_case
     *
     * @mbggenerated Thu Mar 22 17:08:44 CST 2018
     */
    int deleteByExample(CaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_case
     *
     * @mbggenerated Thu Mar 22 17:08:44 CST 2018
     */
    int deleteByPrimaryKey(String card);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_case
     *
     * @mbggenerated Thu Mar 22 17:08:44 CST 2018
     */
    int insert(Case record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_case
     *
     * @mbggenerated Thu Mar 22 17:08:44 CST 2018
     */
    int insertSelective(Case record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_case
     *
     * @mbggenerated Thu Mar 22 17:08:44 CST 2018
     */
    List<Case> selectByExample(CaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_case
     *
     * @mbggenerated Thu Mar 22 17:08:44 CST 2018
     */
    Case selectByPrimaryKey(String card);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_case
     *
     * @mbggenerated Thu Mar 22 17:08:44 CST 2018
     */
    int updateByExampleSelective(@Param("record") Case record, @Param("example") CaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_case
     *
     * @mbggenerated Thu Mar 22 17:08:44 CST 2018
     */
    int updateByExample(@Param("record") Case record, @Param("example") CaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_case
     *
     * @mbggenerated Thu Mar 22 17:08:44 CST 2018
     */
    int updateByPrimaryKeySelective(Case record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_case
     *
     * @mbggenerated Thu Mar 22 17:08:44 CST 2018
     */
    int updateByPrimaryKey(Case record);
}