package cn.zl.dao;

import cn.zl.domain.Credit;
import cn.zl.domain.CreditExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CreditMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_credit
     *
     * @mbggenerated Thu Mar 22 14:09:34 CST 2018
     */
    int countByExample(CreditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_credit
     *
     * @mbggenerated Thu Mar 22 14:09:34 CST 2018
     */
    int deleteByExample(CreditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_credit
     *
     * @mbggenerated Thu Mar 22 14:09:34 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_credit
     *
     * @mbggenerated Thu Mar 22 14:09:34 CST 2018
     */
    int insert(Credit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_credit
     *
     * @mbggenerated Thu Mar 22 14:09:34 CST 2018
     */
    int insertSelective(Credit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_credit
     *
     * @mbggenerated Thu Mar 22 14:09:34 CST 2018
     */
    List<Credit> selectByExample(CreditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_credit
     *
     * @mbggenerated Thu Mar 22 14:09:34 CST 2018
     */
    Credit selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_credit
     *
     * @mbggenerated Thu Mar 22 14:09:34 CST 2018
     */
    int updateByExampleSelective(@Param("record") Credit record, @Param("example") CreditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_credit
     *
     * @mbggenerated Thu Mar 22 14:09:34 CST 2018
     */
    int updateByExample(@Param("record") Credit record, @Param("example") CreditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_credit
     *
     * @mbggenerated Thu Mar 22 14:09:34 CST 2018
     */
    int updateByPrimaryKeySelective(Credit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_credit
     *
     * @mbggenerated Thu Mar 22 14:09:34 CST 2018
     */
    int updateByPrimaryKey(Credit record);
}