package cn.zl.dao;

import cn.zl.domain.Customer;
import cn.zl.domain.CustomerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CustomerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_customer
     *
     * @mbggenerated Thu Mar 22 14:09:34 CST 2018
     */
    int countByExample(CustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_customer
     *
     * @mbggenerated Thu Mar 22 14:09:34 CST 2018
     */
    int deleteByExample(CustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_customer
     *
     * @mbggenerated Thu Mar 22 14:09:34 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_customer
     *
     * @mbggenerated Thu Mar 22 14:09:34 CST 2018
     */
    int insert(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_customer
     *
     * @mbggenerated Thu Mar 22 14:09:34 CST 2018
     */
    int insertSelective(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_customer
     *
     * @mbggenerated Thu Mar 22 14:09:34 CST 2018
     */
    List<Customer> selectByExample(CustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_customer
     *
     * @mbggenerated Thu Mar 22 14:09:34 CST 2018
     */
    Customer selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_customer
     *
     * @mbggenerated Thu Mar 22 14:09:34 CST 2018
     */
    int updateByExampleSelective(@Param("record") Customer record, @Param("example") CustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_customer
     *
     * @mbggenerated Thu Mar 22 14:09:34 CST 2018
     */
    int updateByExample(@Param("record") Customer record, @Param("example") CustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_customer
     *
     * @mbggenerated Thu Mar 22 14:09:34 CST 2018
     */
    int updateByPrimaryKeySelective(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_customer
     *
     * @mbggenerated Thu Mar 22 14:09:34 CST 2018
     */
    int updateByPrimaryKey(Customer record);
}