package cn.zl.dao;

import cn.zl.domain.Enum;
import cn.zl.domain.EnumExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EnumMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_enum
     *
     * @mbggenerated Thu Mar 22 17:08:44 CST 2018
     */
    int countByExample(EnumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_enum
     *
     * @mbggenerated Thu Mar 22 17:08:44 CST 2018
     */
    int deleteByExample(EnumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_enum
     *
     * @mbggenerated Thu Mar 22 17:08:44 CST 2018
     */
    int deleteByPrimaryKey(String key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_enum
     *
     * @mbggenerated Thu Mar 22 17:08:44 CST 2018
     */
    int insert(Enum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_enum
     *
     * @mbggenerated Thu Mar 22 17:08:44 CST 2018
     */
    int insertSelective(Enum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_enum
     *
     * @mbggenerated Thu Mar 22 17:08:44 CST 2018
     */
    List<Enum> selectByExample(EnumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_enum
     *
     * @mbggenerated Thu Mar 22 17:08:44 CST 2018
     */
    Enum selectByPrimaryKey(String key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_enum
     *
     * @mbggenerated Thu Mar 22 17:08:44 CST 2018
     */
    int updateByExampleSelective(@Param("record") Enum record, @Param("example") EnumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_enum
     *
     * @mbggenerated Thu Mar 22 17:08:44 CST 2018
     */
    int updateByExample(@Param("record") Enum record, @Param("example") EnumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_enum
     *
     * @mbggenerated Thu Mar 22 17:08:44 CST 2018
     */
    int updateByPrimaryKeySelective(Enum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_enum
     *
     * @mbggenerated Thu Mar 22 17:08:44 CST 2018
     */
    int updateByPrimaryKey(Enum record);
}