package cn.zl.dao;

import cn.zl.domain.Notice;
import cn.zl.domain.NoticeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NoticeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_notice
     *
     * @mbggenerated Fri Apr 27 18:04:00 CST 2018
     */
    int countByExample(NoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_notice
     *
     * @mbggenerated Fri Apr 27 18:04:00 CST 2018
     */
    int deleteByExample(NoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_notice
     *
     * @mbggenerated Fri Apr 27 18:04:00 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_notice
     *
     * @mbggenerated Fri Apr 27 18:04:00 CST 2018
     */
    int insert(Notice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_notice
     *
     * @mbggenerated Fri Apr 27 18:04:00 CST 2018
     */
    int insertSelective(Notice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_notice
     *
     * @mbggenerated Fri Apr 27 18:04:00 CST 2018
     */
    List<Notice> selectByExample(NoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_notice
     *
     * @mbggenerated Fri Apr 27 18:04:00 CST 2018
     */
    Notice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_notice
     *
     * @mbggenerated Fri Apr 27 18:04:00 CST 2018
     */
    int updateByExampleSelective(@Param("record") Notice record, @Param("example") NoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_notice
     *
     * @mbggenerated Fri Apr 27 18:04:00 CST 2018
     */
    int updateByExample(@Param("record") Notice record, @Param("example") NoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_notice
     *
     * @mbggenerated Fri Apr 27 18:04:00 CST 2018
     */
    int updateByPrimaryKeySelective(Notice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table db_notice
     *
     * @mbggenerated Fri Apr 27 18:04:00 CST 2018
     */
    int updateByPrimaryKey(Notice record);
}