package cn.zl.domain;

import java.util.Date;

public class Approve {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_approve.card
     *
     * @mbggenerated Tue Apr 10 17:44:24 CST 2018
     */
    private String card;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_approve.channel
     *
     * @mbggenerated Tue Apr 10 17:44:24 CST 2018
     */
    private String channel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_approve.id
     *
     * @mbggenerated Tue Apr 10 17:44:24 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_approve.approve
     *
     * @mbggenerated Tue Apr 10 17:44:24 CST 2018
     */
    private String approve;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_approve.approve_time
     *
     * @mbggenerated Tue Apr 10 17:44:24 CST 2018
     */
    private Date approveTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_approve.level
     *
     * @mbggenerated Tue Apr 10 17:44:24 CST 2018
     */
    private Integer level;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_approve.card
     *
     * @return the value of db_approve.card
     *
     * @mbggenerated Tue Apr 10 17:44:24 CST 2018
     */
    public String getCard() {
        return card;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_approve.card
     *
     * @param card the value for db_approve.card
     *
     * @mbggenerated Tue Apr 10 17:44:24 CST 2018
     */
    public void setCard(String card) {
        this.card = card;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_approve.channel
     *
     * @return the value of db_approve.channel
     *
     * @mbggenerated Tue Apr 10 17:44:24 CST 2018
     */
    public String getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_approve.channel
     *
     * @param channel the value for db_approve.channel
     *
     * @mbggenerated Tue Apr 10 17:44:24 CST 2018
     */
    public void setChannel(String channel) {
        this.channel = channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_approve.id
     *
     * @return the value of db_approve.id
     *
     * @mbggenerated Tue Apr 10 17:44:24 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_approve.id
     *
     * @param id the value for db_approve.id
     *
     * @mbggenerated Tue Apr 10 17:44:24 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_approve.approve
     *
     * @return the value of db_approve.approve
     *
     * @mbggenerated Tue Apr 10 17:44:24 CST 2018
     */
    public String getApprove() {
        return approve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_approve.approve
     *
     * @param approve the value for db_approve.approve
     *
     * @mbggenerated Tue Apr 10 17:44:24 CST 2018
     */
    public void setApprove(String approve) {
        this.approve = approve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_approve.approve_time
     *
     * @return the value of db_approve.approve_time
     *
     * @mbggenerated Tue Apr 10 17:44:24 CST 2018
     */
    public Date getApproveTime() {
        return approveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_approve.approve_time
     *
     * @param approveTime the value for db_approve.approve_time
     *
     * @mbggenerated Tue Apr 10 17:44:24 CST 2018
     */
    public void setApproveTime(Date approveTime) {
        this.approveTime = approveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_approve.level
     *
     * @return the value of db_approve.level
     *
     * @mbggenerated Tue Apr 10 17:44:24 CST 2018
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_approve.level
     *
     * @param level the value for db_approve.level
     *
     * @mbggenerated Tue Apr 10 17:44:24 CST 2018
     */
    public void setLevel(Integer level) {
        this.level = level;
    }
}