package cn.zl.domain;

import java.math.BigDecimal;
import java.util.Date;

public class Card {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_card.card
     *
     * @mbggenerated Wed Apr 11 17:39:54 CST 2018
     */
    private String card;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_card.id
     *
     * @mbggenerated Wed Apr 11 17:39:54 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_card.date
     *
     * @mbggenerated Wed Apr 11 17:39:54 CST 2018
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_card.amount
     *
     * @mbggenerated Wed Apr 11 17:39:54 CST 2018
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_card.bill
     *
     * @mbggenerated Wed Apr 11 17:39:54 CST 2018
     */
    private Integer bill;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_card.status
     *
     * @mbggenerated Wed Apr 11 17:39:54 CST 2018
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_card.card
     *
     * @return the value of db_card.card
     *
     * @mbggenerated Wed Apr 11 17:39:54 CST 2018
     */
    public String getCard() {
        return card;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_card.card
     *
     * @param card the value for db_card.card
     *
     * @mbggenerated Wed Apr 11 17:39:54 CST 2018
     */
    public void setCard(String card) {
        this.card = card;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_card.id
     *
     * @return the value of db_card.id
     *
     * @mbggenerated Wed Apr 11 17:39:54 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_card.id
     *
     * @param id the value for db_card.id
     *
     * @mbggenerated Wed Apr 11 17:39:54 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_card.date
     *
     * @return the value of db_card.date
     *
     * @mbggenerated Wed Apr 11 17:39:54 CST 2018
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_card.date
     *
     * @param date the value for db_card.date
     *
     * @mbggenerated Wed Apr 11 17:39:54 CST 2018
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_card.amount
     *
     * @return the value of db_card.amount
     *
     * @mbggenerated Wed Apr 11 17:39:54 CST 2018
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_card.amount
     *
     * @param amount the value for db_card.amount
     *
     * @mbggenerated Wed Apr 11 17:39:54 CST 2018
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_card.bill
     *
     * @return the value of db_card.bill
     *
     * @mbggenerated Wed Apr 11 17:39:54 CST 2018
     */
    public Integer getBill() {
        return bill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_card.bill
     *
     * @param bill the value for db_card.bill
     *
     * @mbggenerated Wed Apr 11 17:39:54 CST 2018
     */
    public void setBill(Integer bill) {
        this.bill = bill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_card.status
     *
     * @return the value of db_card.status
     *
     * @mbggenerated Wed Apr 11 17:39:54 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_card.status
     *
     * @param status the value for db_card.status
     *
     * @mbggenerated Wed Apr 11 17:39:54 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}