package cn.zl.domain;

import java.util.Date;

public class Case {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_case.card
     *
     * @mbggenerated Fri Apr 27 18:04:00 CST 2018
     */
    private String card;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_case.channel
     *
     * @mbggenerated Fri Apr 27 18:04:00 CST 2018
     */
    private String channel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_case.id
     *
     * @mbggenerated Fri Apr 27 18:04:00 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_case.business
     *
     * @mbggenerated Fri Apr 27 18:04:00 CST 2018
     */
    private String business;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_case.deadline
     *
     * @mbggenerated Fri Apr 27 18:04:00 CST 2018
     */
    private Integer deadline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_case.business_time
     *
     * @mbggenerated Fri Apr 27 18:04:00 CST 2018
     */
    private Date businessTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_case.status
     *
     * @mbggenerated Fri Apr 27 18:04:00 CST 2018
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_case.card
     *
     * @return the value of db_case.card
     *
     * @mbggenerated Fri Apr 27 18:04:00 CST 2018
     */
    public String getCard() {
        return card;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_case.card
     *
     * @param card the value for db_case.card
     *
     * @mbggenerated Fri Apr 27 18:04:00 CST 2018
     */
    public void setCard(String card) {
        this.card = card;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_case.channel
     *
     * @return the value of db_case.channel
     *
     * @mbggenerated Fri Apr 27 18:04:00 CST 2018
     */
    public String getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_case.channel
     *
     * @param channel the value for db_case.channel
     *
     * @mbggenerated Fri Apr 27 18:04:00 CST 2018
     */
    public void setChannel(String channel) {
        this.channel = channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_case.id
     *
     * @return the value of db_case.id
     *
     * @mbggenerated Fri Apr 27 18:04:00 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_case.id
     *
     * @param id the value for db_case.id
     *
     * @mbggenerated Fri Apr 27 18:04:00 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_case.business
     *
     * @return the value of db_case.business
     *
     * @mbggenerated Fri Apr 27 18:04:00 CST 2018
     */
    public String getBusiness() {
        return business;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_case.business
     *
     * @param business the value for db_case.business
     *
     * @mbggenerated Fri Apr 27 18:04:00 CST 2018
     */
    public void setBusiness(String business) {
        this.business = business;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_case.deadline
     *
     * @return the value of db_case.deadline
     *
     * @mbggenerated Fri Apr 27 18:04:00 CST 2018
     */
    public Integer getDeadline() {
        return deadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_case.deadline
     *
     * @param deadline the value for db_case.deadline
     *
     * @mbggenerated Fri Apr 27 18:04:00 CST 2018
     */
    public void setDeadline(Integer deadline) {
        this.deadline = deadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_case.business_time
     *
     * @return the value of db_case.business_time
     *
     * @mbggenerated Fri Apr 27 18:04:00 CST 2018
     */
    public Date getBusinessTime() {
        return businessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_case.business_time
     *
     * @param businessTime the value for db_case.business_time
     *
     * @mbggenerated Fri Apr 27 18:04:00 CST 2018
     */
    public void setBusinessTime(Date businessTime) {
        this.businessTime = businessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_case.status
     *
     * @return the value of db_case.status
     *
     * @mbggenerated Fri Apr 27 18:04:00 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_case.status
     *
     * @param status the value for db_case.status
     *
     * @mbggenerated Fri Apr 27 18:04:00 CST 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }
}