package cn.zl.domain;

import java.util.Date;

public class Case {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_case.card
     *
     * @mbggenerated Wed Mar 21 17:48:56 CST 2018
     */
    private String card;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_case.channel
     *
     * @mbggenerated Wed Mar 21 17:48:56 CST 2018
     */
    private String channel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_case.id
     *
     * @mbggenerated Wed Mar 21 17:48:56 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_case.staff
     *
     * @mbggenerated Wed Mar 21 17:48:56 CST 2018
     */
    private String staff;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_case.emergency
     *
     * @mbggenerated Wed Mar 21 17:48:56 CST 2018
     */
    private Integer emergency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_case.deadline
     *
     * @mbggenerated Wed Mar 21 17:48:56 CST 2018
     */
    private Integer deadline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_case.time
     *
     * @mbggenerated Wed Mar 21 17:48:56 CST 2018
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_case.card
     *
     * @return the value of db_case.card
     *
     * @mbggenerated Wed Mar 21 17:48:56 CST 2018
     */
    public String getCard() {
        return card;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_case.card
     *
     * @param card the value for db_case.card
     *
     * @mbggenerated Wed Mar 21 17:48:56 CST 2018
     */
    public void setCard(String card) {
        this.card = card;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_case.channel
     *
     * @return the value of db_case.channel
     *
     * @mbggenerated Wed Mar 21 17:48:56 CST 2018
     */
    public String getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_case.channel
     *
     * @param channel the value for db_case.channel
     *
     * @mbggenerated Wed Mar 21 17:48:56 CST 2018
     */
    public void setChannel(String channel) {
        this.channel = channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_case.id
     *
     * @return the value of db_case.id
     *
     * @mbggenerated Wed Mar 21 17:48:56 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_case.id
     *
     * @param id the value for db_case.id
     *
     * @mbggenerated Wed Mar 21 17:48:56 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_case.staff
     *
     * @return the value of db_case.staff
     *
     * @mbggenerated Wed Mar 21 17:48:56 CST 2018
     */
    public String getStaff() {
        return staff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_case.staff
     *
     * @param staff the value for db_case.staff
     *
     * @mbggenerated Wed Mar 21 17:48:56 CST 2018
     */
    public void setStaff(String staff) {
        this.staff = staff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_case.emergency
     *
     * @return the value of db_case.emergency
     *
     * @mbggenerated Wed Mar 21 17:48:56 CST 2018
     */
    public Integer getEmergency() {
        return emergency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_case.emergency
     *
     * @param emergency the value for db_case.emergency
     *
     * @mbggenerated Wed Mar 21 17:48:56 CST 2018
     */
    public void setEmergency(Integer emergency) {
        this.emergency = emergency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_case.deadline
     *
     * @return the value of db_case.deadline
     *
     * @mbggenerated Wed Mar 21 17:48:56 CST 2018
     */
    public Integer getDeadline() {
        return deadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_case.deadline
     *
     * @param deadline the value for db_case.deadline
     *
     * @mbggenerated Wed Mar 21 17:48:56 CST 2018
     */
    public void setDeadline(Integer deadline) {
        this.deadline = deadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_case.time
     *
     * @return the value of db_case.time
     *
     * @mbggenerated Wed Mar 21 17:48:56 CST 2018
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_case.time
     *
     * @param time the value for db_case.time
     *
     * @mbggenerated Wed Mar 21 17:48:56 CST 2018
     */
    public void setTime(Date time) {
        this.time = time;
    }
}