package cn.zl.domain;

public class Customer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_customer.id
     *
     * @mbggenerated Thu Mar 22 17:08:44 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_customer.phone
     *
     * @mbggenerated Thu Mar 22 17:08:44 CST 2018
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_customer.card
     *
     * @mbggenerated Thu Mar 22 17:08:44 CST 2018
     */
    private String card;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_customer.name
     *
     * @mbggenerated Thu Mar 22 17:08:44 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_customer.gender
     *
     * @mbggenerated Thu Mar 22 17:08:44 CST 2018
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_customer.address
     *
     * @mbggenerated Thu Mar 22 17:08:44 CST 2018
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_customer.level
     *
     * @mbggenerated Thu Mar 22 17:08:44 CST 2018
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_customer.credit
     *
     * @mbggenerated Thu Mar 22 17:08:44 CST 2018
     */
    private Integer credit;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_customer.id
     *
     * @return the value of db_customer.id
     *
     * @mbggenerated Thu Mar 22 17:08:44 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_customer.id
     *
     * @param id the value for db_customer.id
     *
     * @mbggenerated Thu Mar 22 17:08:44 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_customer.phone
     *
     * @return the value of db_customer.phone
     *
     * @mbggenerated Thu Mar 22 17:08:44 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_customer.phone
     *
     * @param phone the value for db_customer.phone
     *
     * @mbggenerated Thu Mar 22 17:08:44 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_customer.card
     *
     * @return the value of db_customer.card
     *
     * @mbggenerated Thu Mar 22 17:08:44 CST 2018
     */
    public String getCard() {
        return card;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_customer.card
     *
     * @param card the value for db_customer.card
     *
     * @mbggenerated Thu Mar 22 17:08:44 CST 2018
     */
    public void setCard(String card) {
        this.card = card;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_customer.name
     *
     * @return the value of db_customer.name
     *
     * @mbggenerated Thu Mar 22 17:08:44 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_customer.name
     *
     * @param name the value for db_customer.name
     *
     * @mbggenerated Thu Mar 22 17:08:44 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_customer.gender
     *
     * @return the value of db_customer.gender
     *
     * @mbggenerated Thu Mar 22 17:08:44 CST 2018
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_customer.gender
     *
     * @param gender the value for db_customer.gender
     *
     * @mbggenerated Thu Mar 22 17:08:44 CST 2018
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_customer.address
     *
     * @return the value of db_customer.address
     *
     * @mbggenerated Thu Mar 22 17:08:44 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_customer.address
     *
     * @param address the value for db_customer.address
     *
     * @mbggenerated Thu Mar 22 17:08:44 CST 2018
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_customer.level
     *
     * @return the value of db_customer.level
     *
     * @mbggenerated Thu Mar 22 17:08:44 CST 2018
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_customer.level
     *
     * @param level the value for db_customer.level
     *
     * @mbggenerated Thu Mar 22 17:08:44 CST 2018
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_customer.credit
     *
     * @return the value of db_customer.credit
     *
     * @mbggenerated Thu Mar 22 17:08:44 CST 2018
     */
    public Integer getCredit() {
        return credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_customer.credit
     *
     * @param credit the value for db_customer.credit
     *
     * @mbggenerated Thu Mar 22 17:08:44 CST 2018
     */
    public void setCredit(Integer credit) {
        this.credit = credit;
    }
}