package cn.zl.domain;

public class Enum {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_enum.key
     *
     * @mbggenerated Wed Mar 21 17:48:56 CST 2018
     */
    private String key;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_enum.value
     *
     * @mbggenerated Wed Mar 21 17:48:56 CST 2018
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_enum.remark
     *
     * @mbggenerated Wed Mar 21 17:48:56 CST 2018
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_enum.key
     *
     * @return the value of db_enum.key
     *
     * @mbggenerated Wed Mar 21 17:48:56 CST 2018
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_enum.key
     *
     * @param key the value for db_enum.key
     *
     * @mbggenerated Wed Mar 21 17:48:56 CST 2018
     */
    public void setKey(String key) {
        this.key = key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_enum.value
     *
     * @return the value of db_enum.value
     *
     * @mbggenerated Wed Mar 21 17:48:56 CST 2018
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_enum.value
     *
     * @param value the value for db_enum.value
     *
     * @mbggenerated Wed Mar 21 17:48:56 CST 2018
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_enum.remark
     *
     * @return the value of db_enum.remark
     *
     * @mbggenerated Wed Mar 21 17:48:56 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_enum.remark
     *
     * @param remark the value for db_enum.remark
     *
     * @mbggenerated Wed Mar 21 17:48:56 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}