package cn.zl.domain;

import java.math.BigDecimal;

public class Level {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_level.level
     *
     * @mbggenerated Thu Mar 22 17:08:44 CST 2018
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_level.max
     *
     * @mbggenerated Thu Mar 22 17:08:44 CST 2018
     */
    private BigDecimal max;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_level.level
     *
     * @return the value of db_level.level
     *
     * @mbggenerated Thu Mar 22 17:08:44 CST 2018
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_level.level
     *
     * @param level the value for db_level.level
     *
     * @mbggenerated Thu Mar 22 17:08:44 CST 2018
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_level.max
     *
     * @return the value of db_level.max
     *
     * @mbggenerated Thu Mar 22 17:08:44 CST 2018
     */
    public BigDecimal getMax() {
        return max;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_level.max
     *
     * @param max the value for db_level.max
     *
     * @mbggenerated Thu Mar 22 17:08:44 CST 2018
     */
    public void setMax(BigDecimal max) {
        this.max = max;
    }
}