package cn.zl.domain;

import java.util.Date;

public class Reset {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_reset.username
     *
     * @mbggenerated Thu Mar 22 17:08:44 CST 2018
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_reset.password
     *
     * @mbggenerated Thu Mar 22 17:08:44 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_reset.resetword
     *
     * @mbggenerated Thu Mar 22 17:08:44 CST 2018
     */
    private String resetword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_reset.reason
     *
     * @mbggenerated Thu Mar 22 17:08:44 CST 2018
     */
    private String reason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_reset.time
     *
     * @mbggenerated Thu Mar 22 17:08:44 CST 2018
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_reset.username
     *
     * @return the value of db_reset.username
     *
     * @mbggenerated Thu Mar 22 17:08:44 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_reset.username
     *
     * @param username the value for db_reset.username
     *
     * @mbggenerated Thu Mar 22 17:08:44 CST 2018
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_reset.password
     *
     * @return the value of db_reset.password
     *
     * @mbggenerated Thu Mar 22 17:08:44 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_reset.password
     *
     * @param password the value for db_reset.password
     *
     * @mbggenerated Thu Mar 22 17:08:44 CST 2018
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_reset.resetword
     *
     * @return the value of db_reset.resetword
     *
     * @mbggenerated Thu Mar 22 17:08:44 CST 2018
     */
    public String getResetword() {
        return resetword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_reset.resetword
     *
     * @param resetword the value for db_reset.resetword
     *
     * @mbggenerated Thu Mar 22 17:08:44 CST 2018
     */
    public void setResetword(String resetword) {
        this.resetword = resetword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_reset.reason
     *
     * @return the value of db_reset.reason
     *
     * @mbggenerated Thu Mar 22 17:08:44 CST 2018
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_reset.reason
     *
     * @param reason the value for db_reset.reason
     *
     * @mbggenerated Thu Mar 22 17:08:44 CST 2018
     */
    public void setReason(String reason) {
        this.reason = reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_reset.time
     *
     * @return the value of db_reset.time
     *
     * @mbggenerated Thu Mar 22 17:08:44 CST 2018
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_reset.time
     *
     * @param time the value for db_reset.time
     *
     * @mbggenerated Thu Mar 22 17:08:44 CST 2018
     */
    public void setTime(Date time) {
        this.time = time;
    }
}