package cn.zl.domain;

import java.util.Date;

public class Staff {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_staff.username
     *
     * @mbggenerated Thu Mar 22 14:09:34 CST 2018
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_staff.password
     *
     * @mbggenerated Thu Mar 22 14:09:34 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_staff.name
     *
     * @mbggenerated Thu Mar 22 14:09:34 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_staff.phone
     *
     * @mbggenerated Thu Mar 22 14:09:34 CST 2018
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_staff.status
     *
     * @mbggenerated Thu Mar 22 14:09:34 CST 2018
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_staff.count
     *
     * @mbggenerated Thu Mar 22 14:09:34 CST 2018
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_staff.time
     *
     * @mbggenerated Thu Mar 22 14:09:34 CST 2018
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_staff.position
     *
     * @mbggenerated Thu Mar 22 14:09:34 CST 2018
     */
    private Integer position;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_staff.username
     *
     * @return the value of db_staff.username
     *
     * @mbggenerated Thu Mar 22 14:09:34 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_staff.username
     *
     * @param username the value for db_staff.username
     *
     * @mbggenerated Thu Mar 22 14:09:34 CST 2018
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_staff.password
     *
     * @return the value of db_staff.password
     *
     * @mbggenerated Thu Mar 22 14:09:34 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_staff.password
     *
     * @param password the value for db_staff.password
     *
     * @mbggenerated Thu Mar 22 14:09:34 CST 2018
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_staff.name
     *
     * @return the value of db_staff.name
     *
     * @mbggenerated Thu Mar 22 14:09:34 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_staff.name
     *
     * @param name the value for db_staff.name
     *
     * @mbggenerated Thu Mar 22 14:09:34 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_staff.phone
     *
     * @return the value of db_staff.phone
     *
     * @mbggenerated Thu Mar 22 14:09:34 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_staff.phone
     *
     * @param phone the value for db_staff.phone
     *
     * @mbggenerated Thu Mar 22 14:09:34 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_staff.status
     *
     * @return the value of db_staff.status
     *
     * @mbggenerated Thu Mar 22 14:09:34 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_staff.status
     *
     * @param status the value for db_staff.status
     *
     * @mbggenerated Thu Mar 22 14:09:34 CST 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_staff.count
     *
     * @return the value of db_staff.count
     *
     * @mbggenerated Thu Mar 22 14:09:34 CST 2018
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_staff.count
     *
     * @param count the value for db_staff.count
     *
     * @mbggenerated Thu Mar 22 14:09:34 CST 2018
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_staff.time
     *
     * @return the value of db_staff.time
     *
     * @mbggenerated Thu Mar 22 14:09:34 CST 2018
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_staff.time
     *
     * @param time the value for db_staff.time
     *
     * @mbggenerated Thu Mar 22 14:09:34 CST 2018
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_staff.position
     *
     * @return the value of db_staff.position
     *
     * @mbggenerated Thu Mar 22 14:09:34 CST 2018
     */
    public Integer getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_staff.position
     *
     * @param position the value for db_staff.position
     *
     * @mbggenerated Thu Mar 22 14:09:34 CST 2018
     */
    public void setPosition(Integer position) {
        this.position = position;
    }
}