package cn.zl.domain;

public class Staff {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_staff.username
     *
     * @mbggenerated Fri Mar 23 17:05:48 CST 2018
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_staff.password
     *
     * @mbggenerated Fri Mar 23 17:05:48 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_staff.name
     *
     * @mbggenerated Fri Mar 23 17:05:48 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_staff.phone
     *
     * @mbggenerated Fri Mar 23 17:05:48 CST 2018
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_staff.image
     *
     * @mbggenerated Fri Mar 23 17:05:48 CST 2018
     */
    private String image;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_staff.status
     *
     * @mbggenerated Fri Mar 23 17:05:48 CST 2018
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_staff.position
     *
     * @mbggenerated Fri Mar 23 17:05:48 CST 2018
     */
    private Integer position;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_staff.username
     *
     * @return the value of db_staff.username
     *
     * @mbggenerated Fri Mar 23 17:05:48 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_staff.username
     *
     * @param username the value for db_staff.username
     *
     * @mbggenerated Fri Mar 23 17:05:48 CST 2018
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_staff.password
     *
     * @return the value of db_staff.password
     *
     * @mbggenerated Fri Mar 23 17:05:48 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_staff.password
     *
     * @param password the value for db_staff.password
     *
     * @mbggenerated Fri Mar 23 17:05:48 CST 2018
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_staff.name
     *
     * @return the value of db_staff.name
     *
     * @mbggenerated Fri Mar 23 17:05:48 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_staff.name
     *
     * @param name the value for db_staff.name
     *
     * @mbggenerated Fri Mar 23 17:05:48 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_staff.phone
     *
     * @return the value of db_staff.phone
     *
     * @mbggenerated Fri Mar 23 17:05:48 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_staff.phone
     *
     * @param phone the value for db_staff.phone
     *
     * @mbggenerated Fri Mar 23 17:05:48 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_staff.image
     *
     * @return the value of db_staff.image
     *
     * @mbggenerated Fri Mar 23 17:05:48 CST 2018
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_staff.image
     *
     * @param image the value for db_staff.image
     *
     * @mbggenerated Fri Mar 23 17:05:48 CST 2018
     */
    public void setImage(String image) {
        this.image = image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_staff.status
     *
     * @return the value of db_staff.status
     *
     * @mbggenerated Fri Mar 23 17:05:48 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_staff.status
     *
     * @param status the value for db_staff.status
     *
     * @mbggenerated Fri Mar 23 17:05:48 CST 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_staff.position
     *
     * @return the value of db_staff.position
     *
     * @mbggenerated Fri Mar 23 17:05:48 CST 2018
     */
    public Integer getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_staff.position
     *
     * @param position the value for db_staff.position
     *
     * @mbggenerated Fri Mar 23 17:05:48 CST 2018
     */
    public void setPosition(Integer position) {
        this.position = position;
    }
}